### PR TITLE
added file pristine zen garden

### PR DESCRIPTION
**Pull request by annagjackson**

### CODE REVIEW

**Comment by Quinn-H** [comment]
Hi, Anna, I suggest you start with
1. delete unnecessary blank space.
2. add blank lines to logical code blocks.
3. add space between divs ending and divs starting.
 You can also use Auto indentation tool to help you tidy HTML code.

**Comment by emma-single** [comment]
It looks like, like me, you did Auto indentation (as ours looks quite similar) and like mine, some of those changes haven't translated to here!

**Review by annagjackson — COMMENTED** [review]
Interesting... I didn't use Auto-Indentation, but some of my formatting still hasn't translated here. I'll try it and see what happens.

**Comment by annagjackson** [comment]
@Quinn-H @emma-single I'm not sure if this is cheating or just being efficient, but I downloaded a package called Beautify and that did the job!

**Comment by Quinn-H** [comment]
@annagjackson  I think tidying is time-consuming work. this is just efficient way to do it.

**Comment by Quinn-H** [comment]
Looks prefect now, I will merge pull request @annagjackson

**Pull request merged**
